/*
 * Velocity-Sandbox
 * API to create a Velocity Sandbox
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alay.vakil@veritas.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Represents an appliance information object
 */
@ApiModel(description = "Represents an appliance information object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-12T22:01:48.152Z")
public class ApplianceDetails {
  @SerializedName("fqdn")
  private String fqdn = null;

  @SerializedName("hostName")
  private String hostName = null;

  @SerializedName("ip")
  private String ip = null;

  public ApplianceDetails fqdn(String fqdn) {
    this.fqdn = fqdn;
    return this;
  }

   /**
   * Fully Qualified Domain Name of an appliance
   * @return fqdn
  **/
  @ApiModelProperty(example = "null", value = "Fully Qualified Domain Name of an appliance")
  public String getFqdn() {
    return fqdn;
  }

  public void setFqdn(String fqdn) {
    this.fqdn = fqdn;
  }

  public ApplianceDetails hostName(String hostName) {
    this.hostName = hostName;
    return this;
  }

   /**
   * Hostname of an Appliance
   * @return hostName
  **/
  @ApiModelProperty(example = "null", value = "Hostname of an Appliance")
  public String getHostName() {
    return hostName;
  }

  public void setHostName(String hostName) {
    this.hostName = hostName;
  }

  public ApplianceDetails ip(String ip) {
    this.ip = ip;
    return this;
  }

   /**
   * IP Address of an appliance
   * @return ip
  **/
  @ApiModelProperty(example = "null", value = "IP Address of an appliance")
  public String getIp() {
    return ip;
  }

  public void setIp(String ip) {
    this.ip = ip;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplianceDetails applianceDetails = (ApplianceDetails) o;
    return Objects.equals(this.fqdn, applianceDetails.fqdn) &&
        Objects.equals(this.hostName, applianceDetails.hostName) &&
        Objects.equals(this.ip, applianceDetails.ip);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fqdn, hostName, ip);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplianceDetails {\n");
    
    sb.append("    fqdn: ").append(toIndentedString(fqdn)).append("\n");
    sb.append("    hostName: ").append(toIndentedString(hostName)).append("\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

