/*
 * Velocity-Sandbox
 * API to create a Velocity Sandbox
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alay.vakil@veritas.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * OracleConfig
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-12T22:01:48.152Z")
public class OracleConfig {
  @SerializedName("databaseName")
  private String databaseName = null;

  @SerializedName("memoryTargetInMB")
  private Long memoryTargetInMB = null;

  @SerializedName("oracleHomePath")
  private String oracleHomePath = null;

  @SerializedName("runtimePath")
  private String runtimePath = null;

  public OracleConfig databaseName(String databaseName) {
    this.databaseName = databaseName;
    return this;
  }

   /**
   * Get databaseName
   * @return databaseName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDatabaseName() {
    return databaseName;
  }

  public void setDatabaseName(String databaseName) {
    this.databaseName = databaseName;
  }

  public OracleConfig memoryTargetInMB(Long memoryTargetInMB) {
    this.memoryTargetInMB = memoryTargetInMB;
    return this;
  }

   /**
   * Get memoryTargetInMB
   * @return memoryTargetInMB
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getMemoryTargetInMB() {
    return memoryTargetInMB;
  }

  public void setMemoryTargetInMB(Long memoryTargetInMB) {
    this.memoryTargetInMB = memoryTargetInMB;
  }

  public OracleConfig oracleHomePath(String oracleHomePath) {
    this.oracleHomePath = oracleHomePath;
    return this;
  }

   /**
   * Get oracleHomePath
   * @return oracleHomePath
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOracleHomePath() {
    return oracleHomePath;
  }

  public void setOracleHomePath(String oracleHomePath) {
    this.oracleHomePath = oracleHomePath;
  }

  public OracleConfig runtimePath(String runtimePath) {
    this.runtimePath = runtimePath;
    return this;
  }

   /**
   * Get runtimePath
   * @return runtimePath
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRuntimePath() {
    return runtimePath;
  }

  public void setRuntimePath(String runtimePath) {
    this.runtimePath = runtimePath;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OracleConfig oracleConfig = (OracleConfig) o;
    return Objects.equals(this.databaseName, oracleConfig.databaseName) &&
        Objects.equals(this.memoryTargetInMB, oracleConfig.memoryTargetInMB) &&
        Objects.equals(this.oracleHomePath, oracleConfig.oracleHomePath) &&
        Objects.equals(this.runtimePath, oracleConfig.runtimePath);
  }

  @Override
  public int hashCode() {
    return Objects.hash(databaseName, memoryTargetInMB, oracleHomePath, runtimePath);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OracleConfig {\n");
    
    sb.append("    databaseName: ").append(toIndentedString(databaseName)).append("\n");
    sb.append("    memoryTargetInMB: ").append(toIndentedString(memoryTargetInMB)).append("\n");
    sb.append("    oracleHomePath: ").append(toIndentedString(oracleHomePath)).append("\n");
    sb.append("    runtimePath: ").append(toIndentedString(runtimePath)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

