/*
 * Velocity-Sandbox
 * API to create a Velocity Sandbox
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alay.vakil@veritas.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.OracleConfig;

/**
 * SandboxConfig
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-12T22:01:48.152Z")
public class SandboxConfig {
  @SerializedName("oracleConfig")
  private OracleConfig oracleConfig = null;

  public SandboxConfig oracleConfig(OracleConfig oracleConfig) {
    this.oracleConfig = oracleConfig;
    return this;
  }

   /**
   * Get oracleConfig
   * @return oracleConfig
  **/
  @ApiModelProperty(example = "null", value = "")
  public OracleConfig getOracleConfig() {
    return oracleConfig;
  }

  public void setOracleConfig(OracleConfig oracleConfig) {
    this.oracleConfig = oracleConfig;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SandboxConfig sandboxConfig = (SandboxConfig) o;
    return Objects.equals(this.oracleConfig, sandboxConfig.oracleConfig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(oracleConfig);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SandboxConfig {\n");
    
    sb.append("    oracleConfig: ").append(toIndentedString(oracleConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

