/*
 * Velocity-Sandbox
 * API to create a Velocity Sandbox
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alay.vakil@veritas.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ApplicationHostInfo;
import io.swagger.client.model.ApplicationInstance;
import io.swagger.client.model.HashMapstringobject;
import io.swagger.client.model.Mount;
import io.swagger.client.model.SandboxConfig;
import io.swagger.client.model.ShareLocation;
import io.swagger.client.model.StatusInfo;
import io.swagger.client.model.User;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a sandbox object
 */
@ApiModel(description = "Represents a sandbox object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-12T22:01:48.152Z")
public class Sandbox {
  @SerializedName("activeShareClientIps")
  private List<String> activeShareClientIps = new ArrayList<String>();

  @SerializedName("applicationHosts")
  private List<ApplicationHostInfo> applicationHosts = new ArrayList<ApplicationHostInfo>();

  @SerializedName("applicationInstance")
  private ApplicationInstance applicationInstance = null;

  @SerializedName("copyPreparation")
  private Boolean copyPreparation = null;

  @SerializedName("creationTime")
  private Long creationTime = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("expiryTime")
  private Long expiryTime = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("mounts")
  private List<Mount> mounts = new ArrayList<Mount>();

  @SerializedName("name")
  private String name = null;

  @SerializedName("owner")
  private User owner = null;

  @SerializedName("pointInTimeCreationTime")
  private Long pointInTimeCreationTime = null;

  @SerializedName("pointInTimeId")
  private String pointInTimeId = null;

  @SerializedName("properties")
  private HashMapstringobject properties = null;

  @SerializedName("sandboxConfig")
  private SandboxConfig sandboxConfig = null;

  @SerializedName("shareLocation")
  private ShareLocation shareLocation = null;

  @SerializedName("sharesOpStateUpdateBatchTime")
  private Long sharesOpStateUpdateBatchTime = null;

  @SerializedName("state")
  private String state = null;

  @SerializedName("statusInfo")
  private StatusInfo statusInfo = null;

  @SerializedName("storageServerId")
  private String storageServerId = null;

  @SerializedName("storageServerRecordId")
  private String storageServerRecordId = null;

  @SerializedName("targetHosts")
  private List<String> targetHosts = new ArrayList<String>();

  @SerializedName("type")
  private String type = null;

  @SerializedName("workloadId")
  private String workloadId = null;

  public Sandbox activeShareClientIps(List<String> activeShareClientIps) {
    this.activeShareClientIps = activeShareClientIps;
    return this;
  }

  public Sandbox addActiveShareClientIpsItem(String activeShareClientIpsItem) {
    this.activeShareClientIps.add(activeShareClientIpsItem);
    return this;
  }

   /**
   * A set of IP addresses of machines that are actively using this share.
   * @return activeShareClientIps
  **/
  @ApiModelProperty(example = "null", value = "A set of IP addresses of machines that are actively using this share.")
  public List<String> getActiveShareClientIps() {
    return activeShareClientIps;
  }

  public void setActiveShareClientIps(List<String> activeShareClientIps) {
    this.activeShareClientIps = activeShareClientIps;
  }

  public Sandbox applicationHosts(List<ApplicationHostInfo> applicationHosts) {
    this.applicationHosts = applicationHosts;
    return this;
  }

  public Sandbox addApplicationHostsItem(ApplicationHostInfo applicationHostsItem) {
    this.applicationHosts.add(applicationHostsItem);
    return this;
  }

   /**
   * For automation releases, added a list of application hosts along with their URI's
   * @return applicationHosts
  **/
  @ApiModelProperty(example = "null", value = "For automation releases, added a list of application hosts along with their URI's")
  public List<ApplicationHostInfo> getApplicationHosts() {
    return applicationHosts;
  }

  public void setApplicationHosts(List<ApplicationHostInfo> applicationHosts) {
    this.applicationHosts = applicationHosts;
  }

  public Sandbox applicationInstance(ApplicationInstance applicationInstance) {
    this.applicationInstance = applicationInstance;
    return this;
  }

   /**
   * Get applicationInstance
   * @return applicationInstance
  **/
  @ApiModelProperty(example = "null", value = "")
  public ApplicationInstance getApplicationInstance() {
    return applicationInstance;
  }

  public void setApplicationInstance(ApplicationInstance applicationInstance) {
    this.applicationInstance = applicationInstance;
  }

  public Sandbox copyPreparation(Boolean copyPreparation) {
    this.copyPreparation = copyPreparation;
    return this;
  }

   /**
   * Flag which indicate Copy Preparation is enabled or not
   * @return copyPreparation
  **/
  @ApiModelProperty(example = "null", value = "Flag which indicate Copy Preparation is enabled or not")
  public Boolean getCopyPreparation() {
    return copyPreparation;
  }

  public void setCopyPreparation(Boolean copyPreparation) {
    this.copyPreparation = copyPreparation;
  }

  public Sandbox creationTime(Long creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * Sandbox creation time
   * @return creationTime
  **/
  @ApiModelProperty(example = "null", required = true, value = "Sandbox creation time")
  public Long getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(Long creationTime) {
    this.creationTime = creationTime;
  }

  public Sandbox description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Short description of the sandbox
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "Short description of the sandbox")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Sandbox expiryTime(Long expiryTime) {
    this.expiryTime = expiryTime;
    return this;
  }

   /**
   * Sandbox expiry time
   * @return expiryTime
  **/
  @ApiModelProperty(example = "null", required = true, value = "Sandbox expiry time")
  public Long getExpiryTime() {
    return expiryTime;
  }

  public void setExpiryTime(Long expiryTime) {
    this.expiryTime = expiryTime;
  }

  public Sandbox id(String id) {
    this.id = id;
    return this;
  }

   /**
   * A unique identifier of the sandbox object
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "A unique identifier of the sandbox object")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Sandbox mounts(List<Mount> mounts) {
    this.mounts = mounts;
    return this;
  }

  public Sandbox addMountsItem(Mount mountsItem) {
    this.mounts.add(mountsItem);
    return this;
  }

   /**
   * Get mounts
   * @return mounts
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Mount> getMounts() {
    return mounts;
  }

  public void setMounts(List<Mount> mounts) {
    this.mounts = mounts;
  }

  public Sandbox name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the sandbox
   * @return name
  **/
  @ApiModelProperty(example = "null", required = true, value = "Name of the sandbox")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Sandbox owner(User owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  @ApiModelProperty(example = "null", value = "")
  public User getOwner() {
    return owner;
  }

  public void setOwner(User owner) {
    this.owner = owner;
  }

  public Sandbox pointInTimeCreationTime(Long pointInTimeCreationTime) {
    this.pointInTimeCreationTime = pointInTimeCreationTime;
    return this;
  }

   /**
   * Time the point-in-time this sandbox is based on was created
   * @return pointInTimeCreationTime
  **/
  @ApiModelProperty(example = "null", required = true, value = "Time the point-in-time this sandbox is based on was created")
  public Long getPointInTimeCreationTime() {
    return pointInTimeCreationTime;
  }

  public void setPointInTimeCreationTime(Long pointInTimeCreationTime) {
    this.pointInTimeCreationTime = pointInTimeCreationTime;
  }

  public Sandbox pointInTimeId(String pointInTimeId) {
    this.pointInTimeId = pointInTimeId;
    return this;
  }

   /**
   * Id of pointInTime for which this sandbox was created
   * @return pointInTimeId
  **/
  @ApiModelProperty(example = "null", required = true, value = "Id of pointInTime for which this sandbox was created")
  public String getPointInTimeId() {
    return pointInTimeId;
  }

  public void setPointInTimeId(String pointInTimeId) {
    this.pointInTimeId = pointInTimeId;
  }

  public Sandbox properties(HashMapstringobject properties) {
    this.properties = properties;
    return this;
  }

   /**
   * Sandbox properties. To be used for any type specific sandbox properties
   * @return properties
  **/
  @ApiModelProperty(example = "null", value = "Sandbox properties. To be used for any type specific sandbox properties")
  public HashMapstringobject getProperties() {
    return properties;
  }

  public void setProperties(HashMapstringobject properties) {
    this.properties = properties;
  }

  public Sandbox sandboxConfig(SandboxConfig sandboxConfig) {
    this.sandboxConfig = sandboxConfig;
    return this;
  }

   /**
   * Get sandboxConfig
   * @return sandboxConfig
  **/
  @ApiModelProperty(example = "null", value = "")
  public SandboxConfig getSandboxConfig() {
    return sandboxConfig;
  }

  public void setSandboxConfig(SandboxConfig sandboxConfig) {
    this.sandboxConfig = sandboxConfig;
  }

  public Sandbox shareLocation(ShareLocation shareLocation) {
    this.shareLocation = shareLocation;
    return this;
  }

   /**
   * Get shareLocation
   * @return shareLocation
  **/
  @ApiModelProperty(example = "null", value = "")
  public ShareLocation getShareLocation() {
    return shareLocation;
  }

  public void setShareLocation(ShareLocation shareLocation) {
    this.shareLocation = shareLocation;
  }

  public Sandbox sharesOpStateUpdateBatchTime(Long sharesOpStateUpdateBatchTime) {
    this.sharesOpStateUpdateBatchTime = sharesOpStateUpdateBatchTime;
    return this;
  }

   /**
   * Get sharesOpStateUpdateBatchTime
   * @return sharesOpStateUpdateBatchTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSharesOpStateUpdateBatchTime() {
    return sharesOpStateUpdateBatchTime;
  }

  public void setSharesOpStateUpdateBatchTime(Long sharesOpStateUpdateBatchTime) {
    this.sharesOpStateUpdateBatchTime = sharesOpStateUpdateBatchTime;
  }

  public Sandbox state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Current state of the sandbox
   * @return state
  **/
  @ApiModelProperty(example = "null", required = true, value = "Current state of the sandbox")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public Sandbox statusInfo(StatusInfo statusInfo) {
    this.statusInfo = statusInfo;
    return this;
  }

   /**
   * More info about the state of the share and why it is in the state it is in
   * @return statusInfo
  **/
  @ApiModelProperty(example = "null", value = "More info about the state of the share and why it is in the state it is in")
  public StatusInfo getStatusInfo() {
    return statusInfo;
  }

  public void setStatusInfo(StatusInfo statusInfo) {
    this.statusInfo = statusInfo;
  }

  public Sandbox storageServerId(String storageServerId) {
    this.storageServerId = storageServerId;
    return this;
  }

   /**
   * A unique identifier of the storage server hosting the sandbox
   * @return storageServerId
  **/
  @ApiModelProperty(example = "null", required = true, value = "A unique identifier of the storage server hosting the sandbox")
  public String getStorageServerId() {
    return storageServerId;
  }

  public void setStorageServerId(String storageServerId) {
    this.storageServerId = storageServerId;
  }

  public Sandbox storageServerRecordId(String storageServerRecordId) {
    this.storageServerRecordId = storageServerRecordId;
    return this;
  }

   /**
   * storage server supplied unique recordId for this sandbox
   * @return storageServerRecordId
  **/
  @ApiModelProperty(example = "null", required = true, value = "storage server supplied unique recordId for this sandbox")
  public String getStorageServerRecordId() {
    return storageServerRecordId;
  }

  public void setStorageServerRecordId(String storageServerRecordId) {
    this.storageServerRecordId = storageServerRecordId;
  }

  public Sandbox targetHosts(List<String> targetHosts) {
    this.targetHosts = targetHosts;
    return this;
  }

  public Sandbox addTargetHostsItem(String targetHostsItem) {
    this.targetHosts.add(targetHostsItem);
    return this;
  }

   /**
   * a list of application hosts for the sandbox
   * @return targetHosts
  **/
  @ApiModelProperty(example = "null", value = "a list of application hosts for the sandbox")
  public List<String> getTargetHosts() {
    return targetHosts;
  }

  public void setTargetHosts(List<String> targetHosts) {
    this.targetHosts = targetHosts;
  }

  public Sandbox type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The type of sandbox.
   * @return type
  **/
  @ApiModelProperty(example = "null", required = true, value = "The type of sandbox.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Sandbox workloadId(String workloadId) {
    this.workloadId = workloadId;
    return this;
  }

   /**
   * Id of workload for which this sandbox was created
   * @return workloadId
  **/
  @ApiModelProperty(example = "null", required = true, value = "Id of workload for which this sandbox was created")
  public String getWorkloadId() {
    return workloadId;
  }

  public void setWorkloadId(String workloadId) {
    this.workloadId = workloadId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sandbox sandbox = (Sandbox) o;
    return Objects.equals(this.activeShareClientIps, sandbox.activeShareClientIps) &&
        Objects.equals(this.applicationHosts, sandbox.applicationHosts) &&
        Objects.equals(this.applicationInstance, sandbox.applicationInstance) &&
        Objects.equals(this.copyPreparation, sandbox.copyPreparation) &&
        Objects.equals(this.creationTime, sandbox.creationTime) &&
        Objects.equals(this.description, sandbox.description) &&
        Objects.equals(this.expiryTime, sandbox.expiryTime) &&
        Objects.equals(this.id, sandbox.id) &&
        Objects.equals(this.mounts, sandbox.mounts) &&
        Objects.equals(this.name, sandbox.name) &&
        Objects.equals(this.owner, sandbox.owner) &&
        Objects.equals(this.pointInTimeCreationTime, sandbox.pointInTimeCreationTime) &&
        Objects.equals(this.pointInTimeId, sandbox.pointInTimeId) &&
        Objects.equals(this.properties, sandbox.properties) &&
        Objects.equals(this.sandboxConfig, sandbox.sandboxConfig) &&
        Objects.equals(this.shareLocation, sandbox.shareLocation) &&
        Objects.equals(this.sharesOpStateUpdateBatchTime, sandbox.sharesOpStateUpdateBatchTime) &&
        Objects.equals(this.state, sandbox.state) &&
        Objects.equals(this.statusInfo, sandbox.statusInfo) &&
        Objects.equals(this.storageServerId, sandbox.storageServerId) &&
        Objects.equals(this.storageServerRecordId, sandbox.storageServerRecordId) &&
        Objects.equals(this.targetHosts, sandbox.targetHosts) &&
        Objects.equals(this.type, sandbox.type) &&
        Objects.equals(this.workloadId, sandbox.workloadId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activeShareClientIps, applicationHosts, applicationInstance, copyPreparation, creationTime, description, expiryTime, id, mounts, name, owner, pointInTimeCreationTime, pointInTimeId, properties, sandboxConfig, shareLocation, sharesOpStateUpdateBatchTime, state, statusInfo, storageServerId, storageServerRecordId, targetHosts, type, workloadId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sandbox {\n");
    
    sb.append("    activeShareClientIps: ").append(toIndentedString(activeShareClientIps)).append("\n");
    sb.append("    applicationHosts: ").append(toIndentedString(applicationHosts)).append("\n");
    sb.append("    applicationInstance: ").append(toIndentedString(applicationInstance)).append("\n");
    sb.append("    copyPreparation: ").append(toIndentedString(copyPreparation)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    expiryTime: ").append(toIndentedString(expiryTime)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    mounts: ").append(toIndentedString(mounts)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    pointInTimeCreationTime: ").append(toIndentedString(pointInTimeCreationTime)).append("\n");
    sb.append("    pointInTimeId: ").append(toIndentedString(pointInTimeId)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    sandboxConfig: ").append(toIndentedString(sandboxConfig)).append("\n");
    sb.append("    shareLocation: ").append(toIndentedString(shareLocation)).append("\n");
    sb.append("    sharesOpStateUpdateBatchTime: ").append(toIndentedString(sharesOpStateUpdateBatchTime)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    statusInfo: ").append(toIndentedString(statusInfo)).append("\n");
    sb.append("    storageServerId: ").append(toIndentedString(storageServerId)).append("\n");
    sb.append("    storageServerRecordId: ").append(toIndentedString(storageServerRecordId)).append("\n");
    sb.append("    targetHosts: ").append(toIndentedString(targetHosts)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    workloadId: ").append(toIndentedString(workloadId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

