/*
 * Velocity-Sandbox
 * API to create a Velocity Sandbox
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alay.vakil@veritas.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ApplianceDetails;

/**
 * Represents a share location object
 */
@ApiModel(description = "Represents a share location object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-12T22:01:48.152Z")
public class ShareLocation {
  @SerializedName("applianceDetails")
  private ApplianceDetails applianceDetails = null;

  @SerializedName("path")
  private String path = null;

  @SerializedName("type")
  private String type = null;

  public ShareLocation applianceDetails(ApplianceDetails applianceDetails) {
    this.applianceDetails = applianceDetails;
    return this;
  }

   /**
   * Get applianceDetails
   * @return applianceDetails
  **/
  @ApiModelProperty(example = "null", value = "")
  public ApplianceDetails getApplianceDetails() {
    return applianceDetails;
  }

  public void setApplianceDetails(ApplianceDetails applianceDetails) {
    this.applianceDetails = applianceDetails;
  }

  public ShareLocation path(String path) {
    this.path = path;
    return this;
  }

   /**
   * Exported share path
   * @return path
  **/
  @ApiModelProperty(example = "null", required = true, value = "Exported share path")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public ShareLocation type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Exported share type, e.g. NFS
   * @return type
  **/
  @ApiModelProperty(example = "null", required = true, value = "Exported share type, e.g. NFS")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShareLocation shareLocation = (ShareLocation) o;
    return Objects.equals(this.applianceDetails, shareLocation.applianceDetails) &&
        Objects.equals(this.path, shareLocation.path) &&
        Objects.equals(this.type, shareLocation.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(applianceDetails, path, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShareLocation {\n");
    
    sb.append("    applianceDetails: ").append(toIndentedString(applianceDetails)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

